spring:
  application:
    name: data-location-service
  data:
    cassandra:
      port: 9042
      contact-points: 127.0.0.1
      keyspace-name: data_location_service
  sleuth:
    stream:
      enabled: false
  cloud:
    config:
      enabled: false
server:
  port: 8081