spring:
  application:
    name: alarm-service
  profiles:
    active: development
  data:
    cassandra:
      port: 9042
      contact-points: 127.0.0.1
      keyspace-name: alarm_service
  cloud:
    stream:
      bindings:
        output:
          destination: requestdata
        input:
          group: alarmservice
          destination: recourceData


server:
  port: 8099
