server:
  port: 8877
spring:
  application:
    name: data-load-service
  cloud:
    stream:
      bindings:
        input:
          destination: requestdata
        output:
          destination: data